### ISSUE TITLE
Change VAPID key challenge to JWT

### ISSUE THREAD

**Issue by martinthomson** [groovecoder/push-dev-dashboard#209]
The challenge that a user signs with their VAPID key is a random string that is entirely under the control of the server.  If not careful, this could be used by a bad server to sign a VAPID token that the server could use to push messages to users.  To avoid this, the signature should include a fixed prefix that the signer can check before applying the signature.

/cc @groovecoder

**Comment by groovecoder** [comment]
Thanks @martinthomson. In Vidyo you had a link to WordPress context managers or something else explaining this bad server vulnerability? Can you link that here too so I can fully understand the issue?

**Comment by martinthomson** [comment]
I have the following spec: https://unicorn-wg.github.io/context-labels/  That includes recommendations on how to create the prefix.

**Comment by groovecoder** [comment]
Hmm ... sorry it's hard for me to unpack the spec and apply it to this context. I'm generating a `uuid4` for the challenge string. So should I add a static prefix to all challenge strings? e.g., `moz-dash-f20cfba1-d87d-403b-af4d-7b5b0601a51a` instead of just `f20cfba1-d87d-403b-af4d-7b5b0601a51a` ?

**Comment by martinthomson** [comment]
The spec recommends a fixed prefix that is at least 12 octets and nul-terminated.  So maybe "Mozilla WebPush Dashboard\0" would do.  You don't need to _send_ the string (and it might in fact be better if you did not.)

BTW, UUID version 4 is fine, but you can also use a really big random number and base64 encoded it.  For example:

``` js
base64 = x => btoa(String.fromCharCode.apply(null, new Uint8Array(x)))
  .replace(/\+/g, '-').replace(/\//g, '_').replace(/={1,2}$/,'');
return base64(crypto.getRandomValues(new Uint8Array(15)))
```

or

``` python
import os
import base64
base64.urlsafe_b64encode(os.urandom(15)).decode()
```

**Comment by groovecoder** [comment]
The current UX requires the developer to copy-paste the token, so a nul-terminated prefix would be a wrench in that machinery. 😞 I can easily prefix the token with `Mozilla-WebPush-Dashboard:` ...
<img width="667" alt="push-dash-key-verification" src="https://cloud.githubusercontent.com/assets/71928/15019331/3fedf73a-11e3-11e6-99e6-fb940d1d0545.png">
But that doesn't seem to mitigate anything, because the prefix is known and constant?

I guess I still don't understand the nature of the vulnerability - how could a bad server use the random token string to send push messages to users? How does a prefix mitigate that?

**Comment by groovecoder** [comment]
Also, is this a security _blocker_ or a security _enhancement_? Need to know if I should spend my time on this, or on the end-to-end test suite for QA.

**Comment by martinthomson** [comment]
What you do is require that the _tool_ that generates the signature knows the string.  You don't put it on the UI.  Or you are just creating a different sort of signing oracle.

> Also, is this a security blocker or a security enhancement? 

I wouldn't ship something without this.

**Comment by groovecoder** [comment]
The only tools we have that generate signatures are [the js and python libraries](https://github.com/mozilla-services/vapid/), and [the wordpress plugin](https://github.com/mozilla/wp-web-push). But we can't guarantee that every VAPID user will use them.

Or we could, but it makes the UX even harder for devs. I.e., instead of "sign this string with your key and paste it back here", the instruction would be "download one of these signing tools, sign this string with your key, and paste it back here."

@clarkbw - can you make the call on whether this is a blocker vs. an enhancement? Can you think of another way to implement a token prefix?

**Comment by clarkbw** [comment]
Here's how I understand it so far.

It would be better for the developers (their security) and ourselves (our own protection) if we only had a prefixed version of the VAPID key such that its not possible for us to use the VAPID key in other contexts.  Meaning we couldn't use if for evil or if we were hacked it couldn't be used by others.

I don't entirely understand how the prefix works.  It sounds like the developers need to be able to verify the prefix on their own so we would need to make it available to them.  That part confuses me a bit.  And then I would guess that our server can only work with keys that have that prefix because it has never seen the naked key.

If I'm understanding this correctly, implementing this later will means we will need developers to come back and setup again when we have the prefix implemented.  I'd rather avoid that scenario.  And seeing as I believe this is something we want (for our mutual protection) I'd say it is more of a blocker than an enhancement.

However I'm open to other sides as I'm not fully understanding the situation.

**Comment by groovecoder** [comment]
I plan to dig into this more tomorrow after adding GA code for https://github.com/mozilla-services/push-dev-dashboard/issues/215.

Since I'm behind on crypto essentials, I want to go thru http://cryptopals.com/ to get my bearings on how the prefix fits everywhere.

Without fully understanding the implications, I'm worried that adding the crypto prefix to tools/libraries will make this a really big piece of work. I.e., we'll need to:
1. Change the autopush server to use the prefix
2. Add code to existing JavaScript, python, and WordPress/PHP libraries to use the prefix
3. Add code to new libraries to use the prefix
4. Forever push (hah!) devs towards these libraries

But, hopefully I'll understand it better after tomorrow. 😄

**Comment by groovecoder** [comment]
@martinthomson - how about this ...

I change tack on how the user/developer verifies their key pair. Instead of asking them to sign a token, I will encrypt the token with their public key and ask them to paste the decrypted token back at me. The UX and effect will be the same, but it doesn't expose a signature.

Sound good?

**Comment by martinthomson** [comment]
Actually, that's really bad.

I have a better suggestion and I'm ashamed to admit that I didn't think of it earlier.  Ask for a new JWT with a different "aud" claim.  The server can specify what the claim should contain.  It doesn't need to be a URI, but you can use one if that makes you feel better (you should have at least 128-bits of randomness in there either way).

Then you just thread this into existing code that generates tokens for use with push.  Does that work for you?

**Comment by martinthomson** [comment]
Just to expand on the "bad" comment:  Cryptographers tell us that a key that is used for signing should not be used for decryption.  With RSA, we know that this is catastrophic.  With EC keys, there isn't a working exploit, but no one has proven that it's safe, so we strongly advise not to do it.

**Comment by groovecoder** [comment]
Ah, yeah that makes the most sense. So, I'll refactor the challenge from a uuid token string to a JWT "aud" claim with at least 128 bits of randomness.

**Comment by groovecoder** [comment]
Alright, I'm refactoring to make the challenge a JWS payload with a unique "aud" claim. I also included code examples for signing the JWT with `python-jose` and `node-jws` libraries, to help developers understand how to do it ...

<img width="720" alt="push-dash-jwt" src="https://cloud.githubusercontent.com/assets/71928/15192442/d6f89568-177e-11e6-8ed3-5ac1fe6558b4.png">

This feels like it makes the UX even harder than signing a simple string, but I'm not sure how else to address it? @clarkbw - any ideas?

**Comment by clarkbw** [comment]
The code samples are helpful.  I'm not sure there is much else we can do.  I did some hunting around and found this: https://github.com/kjur/jsrsasign/wiki/Sample-Node-Script---jwssign but its all a similar amount of steps.
